spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pb_store_db?characterEncoding=utf8
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

dbcp2.jdbc:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/pb_store_db?characterEncoding=utf8
  username: root
  password: password
  initial-size: 1
  max-idle: 3
  min-idle: 1

mybatis:
  mapper-locations: classpath:com/example/pb_store/repository/mybatis/*.xml
